# Generated by Django 5.2 on 2025-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatEstatus',
            fields=[
                ('icodestatus', models.AutoField(db_column='iCodEstatus', primary_key=True, serialize=False)),
                ('tnombre', models.TextField(blank=True, db_column='tNombre', null=True)),
            ],
            options={
                'db_table': 'cat_estatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatGeneros',
            fields=[
                ('icodgenero', models.AutoField(db_column='iCodGenero', primary_key=True, serialize=False)),
                ('tnombre', models.TextField(db_column='tNombre')),
            ],
            options={
                'db_table': 'cat_generos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatPeliculas',
            fields=[
                ('icodpelicula', models.AutoField(db_column='iCodPelicula', primary_key=True, serialize=False)),
                ('tnombre', models.TextField(db_column='tNombre')),
                ('tclasificacion', models.TextField(blank=True, db_column='tClasificacion', null=True)),
                ('dfechaestreno', models.DateField(db_column='dFechaEstreno')),
                ('bactiva', models.IntegerField(db_column='bActiva')),
                ('dtfecharegistro', models.DateTimeField(blank=True, db_column='dtFechaRegistro', null=True)),
            ],
            options={
                'db_table': 'cat_peliculas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatPersonas',
            fields=[
                ('icodpersona', models.AutoField(db_column='iCodPersona', primary_key=True, serialize=False)),
                ('tnombre', models.TextField(db_column='tNombre')),
                ('tnumerotelefonico', models.TextField(blank=True, db_column='tNumeroTelefonico', null=True)),
                ('esexo', models.TextField(db_column='eSexo')),
                ('bactivo', models.IntegerField(db_column='bActivo')),
                ('dfechanacimiento', models.DateField(db_column='dFechaNacimiento')),
                ('dtfecharegistro', models.DateTimeField(db_column='dtFechaRegistro')),
                ('tdireccion', models.TextField(db_column='tDireccion')),
            ],
            options={
                'db_table': 'cat_personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatRoles',
            fields=[
                ('icodrol', models.AutoField(db_column='iCodRol', primary_key=True, serialize=False)),
                ('tnombre', models.TextField(db_column='tNombre')),
                ('bactivo', models.IntegerField(db_column='bActivo')),
            ],
            options={
                'db_table': 'cat_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatSucursales',
            fields=[
                ('icodsucursal', models.AutoField(db_column='iCodSucursal', primary_key=True, serialize=False)),
                ('tnombre', models.TextField(db_column='tNombre')),
                ('tdireccion', models.TextField(blank=True, db_column='tDireccion', null=True)),
                ('bactivo', models.IntegerField(blank=True, db_column='bActivo', null=True)),
            ],
            options={
                'db_table': 'cat_sucursales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProSolicitdesapartados',
            fields=[
                ('icodsolicitudapartado', models.AutoField(db_column='iCodSolicitudApartado', primary_key=True, serialize=False)),
                ('dtfecharegistro', models.DateTimeField(blank=True, db_column='dtFechaRegistro', null=True)),
            ],
            options={
                'db_table': 'pro_solicitdesapartados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProSolicitudesprestamos',
            fields=[
                ('icodsolicitudprestamo', models.AutoField(db_column='iCodSolicitudPrestamo', primary_key=True, serialize=False)),
                ('dfechaprestamo', models.DateField(db_column='dFechaPrestamo')),
                ('dfechadevolucion', models.DateField(blank=True, db_column='dFechaDevolucion', null=True)),
                ('dtfecharegistro', models.DateTimeField(blank=True, db_column='dtFechaRegistro', null=True)),
                ('tobservacion', models.TextField(blank=True, db_column='tObservacion', null=True)),
            ],
            options={
                'db_table': 'pro_solicitudesprestamos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelPeliculascopias',
            fields=[
                ('icodpeliculacopia', models.AutoField(db_column='iCodPeliculaCopia', primary_key=True, serialize=False)),
                ('bactivo', models.IntegerField(db_column='bActivo')),
                ('dfecharegistro', models.DateTimeField(blank=True, db_column='dFechaRegistro', null=True)),
            ],
            options={
                'db_table': 'rel_peliculascopias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelPeliculasgeneros',
            fields=[
                ('icodpeliculagenero', models.AutoField(db_column='iCodPeliculaGenero', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rel_peliculasgeneros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelPeliculaspersonas',
            fields=[
                ('icodpeliculapersona', models.AutoField(db_column='iCodPeliculaPersona', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rel_peliculaspersonas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelPersonasactoresfavoritos',
            fields=[
                ('icodpersonaactorfavorito', models.AutoField(db_column='iCodPersonaActorFavorito', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rel_personasactoresfavoritos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelPersonasdirectoresfavoritos',
            fields=[
                ('icodpersonadirectorfavorito', models.AutoField(db_column='iCodPersonaDirectorFavorito', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rel_personasdirectoresfavoritos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelPersonasgenerosfavoritos',
            fields=[
                ('icodpersonagenerofavorito', models.AutoField(db_column='iCodPersonaGeneroFavorito', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rel_personasgenerosfavoritos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelRolespersonas',
            fields=[
                ('icodrolpersona', models.AutoField(db_column='iCodRolPersona', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rel_rolespersonas',
                'managed': False,
            },
        ),
    ]
